import Head from 'next/head'

interface Props {
  children: React.ReactNode
}

export function BasicLayout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Empareja las cartas 🃏</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <meta name="author" content="Carlos Fernandez Cabrero" />
      </Head>

      <div className="pattern-cross-dots-xl bg-repeat text-[#DBE2EF]/80 min-h-screen">
        <div className="text-[#333]">{children}</div>
      </div>
    </>
  )
}
